x-db-credentials: &db-credentials
  POSTGRES_USER: og_test_app_user
  POSTGRES_PASSWORD: og_test_app_password
  POSTGRES_DB: og_test_app_db
x-db-connect: &db-connect
  DATABASE_HOST: db
  DATABASE_PORT: 5432


services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  api:
    build: ./api
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./api:/app
    environment:
      <<: [
        *db-credentials,
        *db-connect
      ]
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      <<: *db-credentials
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
    db-data:
