services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
#  db:
#    image: postgres:17-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres

